export const userInfoContent = [
    {
        id: 1,
        name: 'Name',
        type: 'text',
        required: true,
        resPath: 'name',
    },
    {
        id: 2,
        name: 'User name',
        type: 'text',
        required: true,
        resPath: 'username',
    },
    {
        id: 3,
        name: 'E-mail',
        type: 'email',
        required: true,
        resPath: 'email',
    },
    {
        id: 4,
        name: 'Street',
        type: 'text',
        required: true,
        resPath: 'address street',
    },
    {
        id: 5,
        name: 'City',
        type: 'text',
        required: true,
        resPath: 'address city',
    },
    {
        id: 6,
        name: 'Phone',
        type: 'tel',
        required: true,
        resPath: 'phone',
    },
    {
        id: 7,
        name: 'Website',
        type: 'url',
        required: true,
        resPath: 'website',
    },
    {
        id: 8,
        name: 'Comment',
        type: 'text',
        required: false,
        resPath: '',
    },
];
